[package]
name = "gdax"
version = "0.1.0"
authors = ["Alexander Polakov <plhk@sdf.org>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
hyper = "0.12"
hyper-tls = "0.3"
tokio = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
